export enum AuditAction {
  LOGIN_FAILED = 'LOGIN_FAILED',
  KPI_EVENT_CREATED = 'KPI_EVENT_CREATED',
  KPI_EVENT_DELETED = 'KPI_EVENT_DELETED',
  KPI_RESULT_CALCULATED = 'KPI_RESULT_CALCULATED',
  KPI_RESULT_CALCULATED_PERIOD = 'KPI_RESULT_CALCULATED_PERIOD',
  KPI_RESULT_APPROVED = 'KPI_RESULT_APPROVED',
  KPI_RESULT_LOCKED = 'KPI_RESULT_LOCKED',
  KPI_RESULT_EXPORTED = 'KPI_RESULT_EXPORTED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
}
